function angleLRmut(ymatrix1)
%CREATEFIGURE1(ymatrix1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 17-Apr-2023 18:04:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1);
set(bar1(2),...
    'FaceColor',[0.729411780834198 0.831372559070587 0.95686274766922]);
set(bar1(1),'FaceColor','none','BarWidth',1);

% Create ylabel
ylabel('Angle [°]');

% Create title
title({'Angle of the right and left branches in the transverese plane','Mutants compared with mean model'});

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',16,'XTick',[3 8.5],'XTickLabel',{'E13.5','E15.5'});
% Create textbox
annotation(figure1,'textbox',...
    [0.122863247863248 0.728732636462405 0.118055558051819 0.140459366779867],...
    'String',{'Mean','model'},...
    'FontSize',16,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.587072649572649 0.718131929748624 0.118055558051819 0.140459366779867],...
    'String',{'Mean','model'},...
    'FontSize',16,...
    'EdgeColor','none');

